version: '3.3'

services:
  limon:
    build:
      context: ./limon
      dockerfile: Dockerfile.test
    ports: ["5000:5000"]
    container_name: limon
    volumes:
      - /proc:/proc

  mysql:
    image: mysql:latest
    container_name: mysql
    ports: ["3306:3306"]
    environment:
      #values changed on first run
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
